apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-pipeline
  description: "A Jenkins test pipeline that generates dummy logs."
  annotations:
    jenkins.io/job-full-name: "test-pipeline"
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: devsecops-team
  system: cicd
  dependsOn:
    - resource:jenkins
